### PR TITLE
Pride

### PR DESCRIPTION
**Pull request by Malacath-92**
Added a bunch of pride flags as an easter egg for the upcoming greatest month of the year  😛

### CODE REVIEW

**Comment by gmjosack** [comment]
This is really cool but one concern is with the way the input and rng is implemented. The way the service serves these images is they are aggressively cached so once the first image is generated we won't see other variance. That's not so bad for the sizes that only have one flag type but the ones that are 50/50 will just continue to serve the first one that was generated.

I wonder if it'd make sense to do this as a query param on top of the normal name but the variance on some are pretty small so I'm not quite sure the best way to handle it. Thoughts?

**Comment by Malacath-92** [comment]
Hehe, yeah, I thought about the caching in particular and wanted to write something about it but was quite busy today, I was just glad I got this done finally  😅
Two ideas I had for that:
- first one was basically what you described, when the discord-bot receives the input that generates the easter egg it could do the equivalent of !random, then add another param on top. But it would be a ton of duplicate data since many have barely any variation. But if we do also the 50/50 as a param on top instead we could probably make sure that we only cache one-per-variant as well?
- second one might just be naïve as I know nothing about the backend of caching. If you could cache a couple versions (say 10) and hand those out you would have a good chance the variations are there. Or you make it clear the cache after some minutes/hours when the same image is requested. I don't know if either of these is reasonable.

Was also gonna mention the sizes (as I had to introduce new sizes for variety's sake). If you won't want to add these odd sizes to the bot we could additionally randomly choose 3 or 4 for small, 5 or 6 for regular and 7 or 8 for big.

On that note, I wanted to make regular spelunkicons work for odd sizes too, I forgot about that. Probably just make the center plane independent and the mirror only on the outer parts.

**Comment by gmjosack** [comment]
I don't pay anything for caching, just helps keep load off the server but I don't mind serving the requests, they're pretty cheap. If we make it so the interface to the bot is just

```
!spelunkicon !pride
```

then we could just randomize the size and input string in which case it'd probably make more sense to use `pride` as a query param rather than as the input string.

**Comment by Malacath-92** [comment]
Made it into a param now, there's room for more eggs if I feel silly some day  😛  Does this align with what you were thinking? Rng can now also go back to using the same seed.

And I made regular spelunkicons work for odd sizes as well by adding another N bytes that are used only on the center column.

**Pull request merged**
